# ── Dracula Theme ───────────────────────────────
# https://draculatheme.com

$rosewater = rgb(f8f8f2)
$flamingo  = rgb(f8f8f2)
$pink      = rgb(ff79c6)
$mauve     = rgb(bd93f9)
$red       = rgb(ff5555)
$maroon    = rgb(ff5555)
$peach     = rgb(ffb86c)
$yellow    = rgb(f1fa8c)
$green     = rgb(50fa7b)
$teal      = rgb(8be9fd)
$sky       = rgb(8be9fd)
$sapphire  = rgb(6272a4)
$blue      = rgb(bd93f9)
$lavender  = rgb(6272a4)
$text      = rgb(f8f8f2)
$subtext1  = rgb(e0e0e0)
$subtext0  = rgb(bfbfbf)
$overlay2  = rgb(6272a4)
$overlay1  = rgb(566190)
$overlay0  = rgb(44475a)
$surface2  = rgb(44475a)
$surface1  = rgb(383a4a)
$surface0  = rgb(313341)
$base      = rgb(282a36)
$mantle    = rgb(21222c)
$crust     = rgb(191a21)
