# ── Gruvbox Dark Theme ──────────────────────────
# https://github.com/morhetz/gruvbox

$rosewater = rgb(d5c4a1)
$flamingo  = rgb(d5c4a1)
$pink      = rgb(d3869b)
$mauve     = rgb(d3869b)
$red       = rgb(fb4934)
$maroon    = rgb(cc241d)
$peach     = rgb(fe8019)
$yellow    = rgb(fabd2f)
$green     = rgb(b8bb26)
$teal      = rgb(8ec07c)
$sky       = rgb(83a598)
$sapphire  = rgb(83a598)
$blue      = rgb(83a598)
$lavender  = rgb(bdae93)
$text      = rgb(ebdbb2)
$subtext1  = rgb(d5c4a1)
$subtext0  = rgb(bdae93)
$overlay2  = rgb(a89984)
$overlay1  = rgb(928374)
$overlay0  = rgb(7c6f64)
$surface2  = rgb(665c54)
$surface1  = rgb(504945)
$surface0  = rgb(3c3836)
$base      = rgb(282828)
$mantle    = rgb(1d2021)
$crust     = rgb(1d2021)
