# ── Nord Theme ──────────────────────────────────
# https://www.nordtheme.com

$rosewater = rgb(d8dee9)
$flamingo  = rgb(d8dee9)
$pink      = rgb(b48ead)
$mauve     = rgb(b48ead)
$red       = rgb(bf616a)
$maroon    = rgb(bf616a)
$peach     = rgb(d08770)
$yellow    = rgb(ebcb8b)
$green     = rgb(a3be8c)
$teal      = rgb(8fbcbb)
$sky       = rgb(88c0d0)
$sapphire  = rgb(81a1c1)
$blue      = rgb(81a1c1)
$lavender  = rgb(5e81ac)
$text      = rgb(eceff4)
$subtext1  = rgb(e5e9f0)
$subtext0  = rgb(d8dee9)
$overlay2  = rgb(9aa3b5)
$overlay1  = rgb(7b8496)
$overlay0  = rgb(616a7a)
$surface2  = rgb(4c566a)
$surface1  = rgb(434c5e)
$surface0  = rgb(3b4252)
$base      = rgb(2e3440)
$mantle    = rgb(292e39)
$crust     = rgb(242933)
