# ── Tokyo Night Theme ───────────────────────────
# https://github.com/enkia/tokyo-night-vscode-theme

$rosewater = rgb(c0caf5)
$flamingo  = rgb(c0caf5)
$pink      = rgb(bb9af7)
$mauve     = rgb(bb9af7)
$red       = rgb(f7768e)
$maroon    = rgb(db4b4b)
$peach     = rgb(ff9e64)
$yellow    = rgb(e0af68)
$green     = rgb(9ece6a)
$teal      = rgb(73daca)
$sky       = rgb(7dcfff)
$sapphire  = rgb(7aa2f7)
$blue      = rgb(7aa2f7)
$lavender  = rgb(c0caf5)
$text      = rgb(a9b1d6)
$subtext1  = rgb(9aa5ce)
$subtext0  = rgb(787c99)
$overlay2  = rgb(565f89)
$overlay1  = rgb(414868)
$overlay0  = rgb(3b4261)
$surface2  = rgb(33467c)
$surface1  = rgb(292e42)
$surface0  = rgb(232433)
$base      = rgb(1a1b26)
$mantle    = rgb(16161e)
$crust     = rgb(13131a)
